jobs:
  ocp-version:
    runs-on: ubuntu-latest
    env:
      TEST_TO_TRIGGER_FILE_PATH: "workflows/generatble-files/tests_to_trigger.txt"
      NEW_VERSION_FILE_PATH: "workflows/generatble-files/file.json"
    steps:
      - name: Check out the Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Update OCP Version
        run: |
          pip install -r workflows/requirements.txt
          mkdir -p $(dirname ${NEW_VERSION_FILE_PATH})  # Ensure directory exists
          echo '{}' > ${NEW_VERSION_FILE_PATH}
          python workflows/update_ocp_version.py workflows/versions.json
          python workflows/update_gpu_bundle.py workflows/versions.json

      - name: Read Test Trigger File
        id: read_tests
        run: |
          {
            echo 'TEST_TRIGGERS<<EOF'
            cat ${TEST_TO_TRIGGER_FILE_PATH}
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[Automatic] Update versions"
          commit-message: Update versions
          body: |
            :warning: Before approving the PR, the following tests should be run:

            ```
            ${{ steps.read_tests.outputs.TEST_TRIGGERS }}
            ```

            Updates version of the OCP version
          delete-branch: true
          assignees: empovit,TomerNewman
